site_name: RSDK Modding Wiki
site_description: Retro Engine modding guides and tools
repo_url: https://github.com/RSDKModding/RSDK-Modding-Wiki
repo_name: RSDK-Modding-Wiki
theme:
  name: material
  logo: assets/RSDK_Logo.svg
  favicon: assets/RSDK_Icon_Color.svg
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - rsdk_theme/colors.css
  - rsdk_theme/background.css
  - rsdk_theme/header.css
  - rsdk_theme/body.css
extra_javascript:
  - rsdk_theme/background.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: README.md
  - Retro Engine:
    - Intro:
      - Intro/README.md

    - RSonic:
      - RSonic/README.md

    - Nexus:
      - Nexus/README.md

    - RSDKv3:
      - RSDKv3/README.md
      - Documentation:
        - Overview: RSDKv3/Overview/README.md
        - Events: RSDKv3/Events/README.md
        - Functions:
          - RSDKv3/Functions/README.md
          - RSDKv3/Functions/README.md

    - RSDKv4:
      - RSDKv4/README.md
      - Documentation:
        - Overview: RSDKv4/Overview/README.md
        - Events: RSDKv4/Events/README.md
        - Functions: RSDKv4/Functions/README.md

    - RSDKv5:
      - RSDKv5/README.md
      - Documentation:
        - Overview: RSDKv5/Overview/README.md
        - Events: RSDKv5/Events/README.md
        - Functions: RSDKv5/Functions/README.md

  - Tools:
    - RSDK Anim Editor:
      - Tools/RSDK-Anim-Editor/README.md

