authors:
  megami:
    name: MegAmi
    description: RSDK Modder, Decompilation Maintainer
    avatar: https://github.com/megami24.png
    url: https://github.com/megami24
  mefiresu:
    name: Mefiresu
    description: Decompilation Maintainer
    avatar: https://github.com/mefiresu.png
    url: https://github.com/mefiresu