name: github-pages-deploy
on:
  push:
    paths:
      - docs/**
      - .github/github-pages-deploy.yml
      - mkdocs.yml
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force